# Generated by Django 4.2.27 on 2026-01-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('still', models.FileField(blank=True, help_text='An image that will be used as a thumbnail.', upload_to='audio_stills')),
                ('audio', models.FilePathField(path='/Users/bturner/projects/mysite/mysite/media/audios/', recursive=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'audios',
                'db_table': 'media_audio',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('photo', models.FileField(upload_to='photos')),
                ('taken_by', models.CharField(blank=True, max_length=100)),
                ('license', models.URLField(blank=True, choices=[('http://creativecommons.org/licenses/by/2.0/', 'CC Attribution'), ('http://creativecommons.org/licenses/by-nd/2.0/', 'CC Attribution-NoDerivs'), ('http://creativecommons.org/licenses/by-nc-nd/2.0/', 'CC Attribution-NonCommercial-NoDerivs'), ('http://creativecommons.org/licenses/by-nc/2.0/', 'CC Attribution-NonCommercial'), ('http://creativecommons.org/licenses/by-nc-sa/2.0/', 'CC Attribution-NonCommercial-ShareAlike'), ('http://creativecommons.org/licenses/by-sa/2.0/', 'CC Attribution-ShareAlike')])),
                ('description', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('_exif', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'media_photos',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('still', models.FileField(blank=True, help_text='An image that will be used as a thumbnail.', upload_to='video_stills')),
                ('video', models.FilePathField(path='/Users/bturner/projects/mysite/mysite/media/videos/', recursive=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_videos',
            },
        ),
        migrations.CreateModel(
            name='VideoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('videos', models.ManyToManyField(related_name='video_sets', to='media.video')),
            ],
            options={
                'db_table': 'media_video_sets',
            },
        ),
        migrations.CreateModel(
            name='PhotoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.photo')),
                ('photos', models.ManyToManyField(related_name='photo_sets', to='media.photo')),
            ],
            options={
                'db_table': 'media_photo_sets',
            },
        ),
        migrations.CreateModel(
            name='AudioSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('audios', models.ManyToManyField(related_name='audio_sets', to='media.audio')),
            ],
            options={
                'db_table': 'media_audio_sets',
            },
        ),
    ]
