# Generated by Django 4.2.27 on 2026-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
