# Generated by Django 4.2.27 on 2026-01-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_audio_file_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FilePathField(blank=True, path='/Users/bturner/projects/mysite/mysite/media/audios/', recursive=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FilePathField(blank=True, path='/Users/bturner/projects/mysite/mysite/media/videos/', recursive=True),
        ),
    ]
