# Generated by Django 4.2.27 on 2026-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_audio_audio_alter_audio_file_alter_video_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-uploaded',)},
        ),
        migrations.AddField(
            model_name='photo',
            name='content_type',
            field=models.IntegerField(choices=[(1, 'Photo'), (2, 'Screenshot'), (3, 'Illustration')], default=1),
        ),
    ]
